FROM ghcr.io/ublue-os/ubuntu-toolbox

LABEL com.github.containers.toolbox="true" \
    name="claude-toolbox" \
    usage="This image is meant to be used with the Toolbox or Distrobox commands." \
    summary="The ublue-os ubuntu-toolbox, fattened to run dev stuff with Claude." \
    maintainer=""

# Bring base image up-to-date
RUN apt-get update && apt-get upgrade -y && apt autoremove -y

# Add additional packages
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
        gh \
        golang \
        jq yq \
        python3 python3-pip python-is-python3 pipx && \
    # Cleanup
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Starship
RUN curl -sS https://starship.rs/install.sh -o install_starship.sh && \
    sh install_starship.sh -y && \
    rm -f install_starship.sh

# Install uv (modern Python package manager)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Install Node.js -- creates:
#   tree -d -L 1 /usr/lib/node_modules/
#   /usr/lib/node_modules/
#   |-- corepack
#   `-- npm
#
#   /usr/bin/... -- executable symlinks point to related package bins in above tree
RUN curl -fsSL https://deb.nodesource.com/setup_24.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs && \
    rm -f nodesource_setup.sh

# Install global dev-related node packages
RUN npm i -g npm-check-updates && \
    npm i -g eslint && \
    npm i -g typescript && \
    npm i -g pyright

# Install Playwright and Chrome
# 1. Install system deps (Ubuntu libraries), without browsers
RUN npx playwright install-deps chromium
# 2. Install Playwright-bundled chromium into local image
# see https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.noble
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN mkdir $PLAYWRIGHT_BROWSERS_PATH && \
    mkdir "${PLAYWRIGHT_BROWSERS_PATH}-agent" && \
    cd "${PLAYWRIGHT_BROWSERS_PATH}-agent" && npm init -y && \
    npm i -D @playwright/test && \
    npm exec --no -- playwright-core install chromium && \
    rm -rf "${PLAYWRIGHT_BROWSERS_PATH}-agent" && \
    chmod -R 777 $PLAYWRIGHT_BROWSERS_PATH
# 3. Install Playwright stock Google Chrome into local image at /usr/bin/google-chrome, also
# installs ffmpeg into /root/.cache, can delete this, we have it already in /ms-playwright
RUN npx playwright install chrome

# Install Claude Code
RUN curl -fsSL https://claude.ai/install.sh  -o install_claude.sh && \
    bash install_claude.sh && \
    # creates a symlink /root/.local/bin/claude -> /root/.local/bin/claude/versions/x.y.z
    # move it into system path, and make the target path readable
    mv /root/.local/bin/claude /usr/local/bin && \
    chmod go+rx /root && \
    # cleanup
    rm -f install_claude.sh && \
    rm -rf /root/.claude && \
    rm -f /root/.claude.json*

# Install Gemmini CLI
RUN npm i -g @google/gemini-cli

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.npm && \
    rm -rf /root/.cache
